namespace GameBoxSdk.Runtime.Sound
{
	public class ClipIds
	{
		// This file is auto generated from the ClipsDatabase Scriptable Object
		// DO NOT EDIT THIS FILE MANUALLY
		public const string COIN_CLIP = "CoinClip";
		public const string MUSIC_CLIP = "MusicClip";
		public const string BUTTON_CLICK_CLIP = "ButtonClickClip";
		public const string AIRCRAFT_ENGINE_CLIP = "AircraftEngineClip";
		public const string AIRCRAFT_EXPLOSION_CLIP = "AircraftExplosionClip";
		public const string FUEL_CLIP = "FuelClip";
		public const string MAGNET_CLIP = "MagnetClip";
		public const string SHIELD_CLIP = "ShieldClip";
		public const string SPEED_BOOSTER_CLIP = "SpeedBoosterClip";
		public const string COIN_MULTIPLIER_CLIP = "CoinMultiplierClip";
	}
}

