namespace RacingGameDemo.Runtime.Gameplay.Car
{
	public enum CarIds
	{
		// This file is auto generated from the ClipsDatabase Scriptable Object
		// DO NOT EDIT THIS FILE MANUALLY
		None,
		CarA,
		CarB,
	}
}

