namespace RacingGameDemo.Runtime.Gameplay.Track
{
	public enum TrackIds
	{
		// This file is auto generated from the ClipsDatabase Scriptable Object
		// DO NOT EDIT THIS FILE MANUALLY
		None,
		TrackA,
	}
}

