namespace GameBoxSdk.Runtime.UI.Views
{
	public class ViewIds
	{
		// This file is auto generated from the ViewsDatabase Scriptable Object
		// DO NOT EDIT THIS FILE MANUALLY
		public const string MAIN_MENU = "MainMenu";
	}
}

