namespace GameBoxSdk.Runtime.UI.Views
{
	public enum ViewIds
	{
		// This file is auto generated from the ViewsDatabase Scriptable Object
		// DO NOT EDIT THIS FILE MANUALLY
		None,
		MainMenu,
		CarSelection,
		LoadingScreen,
	}
}

