namespace GameBoxSdk.Runtime.Localization
{
	public class LanguageIds
	{
		// This file is auto generated from the ViewsDatabase Scriptable Object
		// DO NOT EDIT THIS FILE MANUALLY
		public const string ENGLISH = "English";
		public const string FRENCH = "French";
		public const string SPANISH = "Spanish";
	}
}

