namespace GameBoxSdk.Runtime.Localization
{
	public enum LanguageIds
	{
		// This file is auto generated from the ViewsDatabase Scriptable Object
		// DO NOT EDIT THIS FILE MANUALLY
		None,
		English,
	}
}

